### ISSUE TITLE
Game crashed in 1.15.2 after eating Confit Byaldi, conflict with apotheosis

### ISSUE THREAD

**Issue by Ratmonster04** [AlexModGuy/Rats#243]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/22/20 4:19 PM
Description: Ticking player

java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.assertThread(SourceFile:81) ~[?:?] {re:classloading}
	at net.minecraft.client.shader.Framebuffer.func_147608_a(SourceFile:72) ~[?:?] {re:classloading}
	at net.minecraft.client.shader.ShaderGroup.close(ShaderGroup.java:263) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_181022_b(GameRenderer.java:111) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at hugman.mubble.objects.event_handler.ShaderHandler.onArmorChange(ShaderHandler.java:33) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_363_ShaderHandler_onArmorChange_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:315) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2023) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:hammerlib:coremodone}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:hammerlib:coremodone}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
Here is the crash report. I was playing the mod I ate confit byaldi the game crashed and I could not get back into the game. I think it was because of the effect that happens after you eat it or it was because I had a ton of mods I would like to see this fixed.

**Comment by Alex-the-666** [comment]
something believes me to believe apothesis mod might be a cause, since
>apotheosis:apothshieldblock

is included in the crash and i was able to eat confit byaldi without crashing in a fresh install.

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
