### ISSUE TITLE
1.16 crash when you hit a rat 

### ISSUE THREAD

**Issue by Dracux** [AlexModGuy/Rats#354]
Description: Ticking entity

java.lang.NoSuchMethodError: com.github.alexthe666.rats.server.entity.EntityRat.func_184215_y(Lnet/minecraft/entity/Entity;)Z
	at com.github.alexthe666.rats.server.entity.EntityRat.func_213336_c(EntityRat.java:3165) ~[?:6.0.4-1.16.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.EntityPredicate.func_221015_a(SourceFile:74) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.TargetGoal.func_220777_a(SourceFile:104) ~[?:?] {re:classloading}
	at com.github.alexthe666.rats.server.entity.ai.RatAIOwnerHurtTarget.func_75250_a(RatAIOwnerHurtTarget.java:35) ~[?:6.0.4-1.16.1] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_252] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_252] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_252] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_252] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_252] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_252] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_252] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_252] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_252] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:77) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:678) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:487) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:126) ~[?:?] {re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:50) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:946) ~[?:6.0.4-1.16.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2157) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:299) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70098_U(EntityRat.java:2147) ~[?:6.0.4-1.16.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217459_a(ServerWorld.java:631) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:596) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:791) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.rats.server.entity.EntityRat.func_213336_c(EntityRat.java:3165)
	at net.minecraft.entity.EntityPredicate.func_221015_a(SourceFile:74)
	at net.minecraft.entity.ai.goal.TargetGoal.func_220777_a(SourceFile:104)
	at com.github.alexthe666.rats.server.entity.ai.RatAIOwnerHurtTarget.func_75250_a(RatAIOwnerHurtTarget.java:35)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:77)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:678)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:487)
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:126)
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:50)
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:946)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2157)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:299)
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70098_U(EntityRat.java:2147)
	at net.minecraft.world.server.ServerWorld.func_217459_a(ServerWorld.java:631)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)

-- Entity being ticked --
Details:
	Entity Type: rats:rat_mount_golem (com.github.alexthe666.rats.server.entity.EntityRatGolemMount)
	Entity ID: 1
	Entity Name: Rat Golem Mount
	Entity's Exact location: 237.00, 62.00, 250.64
	Entity's Block location: World: (237,62,250), Chunk: (at 13,3,10 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.01, -0.08, -0.07
	Entity's Passengers: [EntityRat['Rat'/2, l='ServerLevel[world]', x=236.98, y=64.05, z=250.87]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:596)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Dracux'/375, l='ServerLevel[world]', x=244.88, y=62.00, z=243.30]]
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,67,256), Chunk: (at 0,4,0 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4281865 game time, 4281865 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 8049 (now: true), thunder time: 7501 (now: true)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:791)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 4.9.0-12-amd64
	Java Version: 1.8.0_252, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 144579176 bytes (137 MB) / 618172416 bytes (589 MB) up to 2138767360 bytes (2039 MB)
	CPUs: 1
	JVM Flags: 5 total; -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UnlockExperimentalVMOptions -Xmx2048M -Xms512M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.57.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.57.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.57.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.57.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.57.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.57
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.57-server.jar Minecraft {minecraft@1.16.1 DONE}
		dwarfcoal-1.16.1-1.1.jar Dwarf Coal {dwarfcoal@1.16.1-1.0.0 DONE}
		useful_backpacks-1.16.1-1.11.0.68-SNAPSHOT.jar Useful Backpacks {usefulbackpacks@1.11.0.68-SNAPSHOT DONE}
		dotHack-Weapons-1.16.1-1.0.0.jar dotHack Weapons {dothack@1.0.0 DONE}
		giantspawn_1.16-2.1.jar Giant Spawn {giantspawn@2.1 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		breedablekr_1.16-1.1.jar Breedable Killer Rabbit {breedablekr@1.1 DONE}
		car-1.16.1-1.0.3.jar Ultimate Car Mod {car@1.16.1-1.0.3 DONE}
		AzureDooms-Doom-Mod-1.16.1-1.2.0.jar Azuredooms Doom Mod {doomweapon@1.2.0 DONE}
		collective-1.16.1-1.35.jar Collective {collective@1.35 DONE}
		ElementsOfPower-1.16.1-0.10.0-alpha.jar Elements of Power {elementsofpower@0.10.0-alpha DONE}
		NastyMobs-1.16.1-1.0.0.3.jar Nasty Mobs {nasty@1.0.0.3 DONE}
		citadel-1.2.0.jar Citadel {citadel@1.2.0 DONE}
		rats-6.0.4-1.16.1.jar Rats {rats@6.0.4 DONE}
		Animalium-0.6.0.jar Animalium {animalium@0.6.0 DONE}
		engineerstools-1.16.1-1.0.8-a1.jar Engineer's Tools {engineerstools@1.0.8-a1 DONE}
		guardvillagers-1.16.1-1.1.0.jar Guard Villagers {guardvillagers@1.0.7 DONE}
		u_team_core-1.16.1-3.1.0.161-SNAPSHOT.jar U Team Core {uteamcore@3.1.0.161-SNAPSHOT DONE}
		japanese_food_mod-1.16.1-1.0.2.jar japanese_food_mod {japanese_food_mod@1.16.1-1.0.2 DONE}
		productivebees-1.16.1-0.1.13.jar Productive Bees {productivebees@1.16.1-0.1.13 DONE}
		enchantwithmob-1.16.1-1.0.1.jar Enchant With Mob {enchantwithmob@1.16.1-1.0.1 DONE}
		firstaid-1.9.1.jar First Aid {firstaid@1.9.1 DONE}
		forge-1.16.1-32.0.57-universal.jar Forge {forge@32.0.57 DONE}
		SolarGeneration-1.16.1-2.0.0.jar Solar Generation {solargeneration@2.0.0 DONE}
		supertools-1.16.1-2.jar Vanilla+ Tools {supertools@version DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		xptome-1.16.1-v1.1.5.jar XP Tome {xpbook@v1.1.5 DONE}
		bigbuckets-1.1.1.jar BigBuckets {bigbuckets@1.1.1 DONE}
	Player Count: 1 / 999; [ServerPlayerEntity['Dracux'/375, l='ServerLevel[world]', x=244.88, y=62.00, z=243.30]]
	Data Packs: vanilla, mod:animalium (incompatible), mod:bigbuckets (incompatible), mod:breedablekr, mod:car, mod:citadel (incompatible), mod:collective, mod:doomweapon, mod:dothack, mod:dwarfcoal (incompatible), mod:elementsofpower, mod:enchantwithmob, mod:engineerstools, mod:firstaid (incompatible), mod:forge (incompatible), mod:giantspawn, mod:guardvillagers (incompatible), mod:ironchest, mod:japanese_food_mod (incompatible), mod:jei (incompatible), mod:nasty, mod:productivebees, mod:rats (incompatible), mod:solargeneration, mod:supertools (incompatible), mod:usefulbackpacks, mod:uteamcore, mod:xpbook
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFoundError errors are something I haven't been able to reproduce. These methods should exist, especially when it comes to AI tasks, so there's definitely something else going on here. Closing as this is something I can't exactly deal with without more context
