### ISSUE TITLE
When a skeletal rat tries to hit a monster, the game crashes. Rats 6.0.5

### ISSUE THREAD

**Issue by ntaklive** [AlexModGuy/Rats#389]
When a skeletal rat tries to hit a monster, the game crashes. Rats 6.0.5

 ---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 03.08.20 17:43
Description: Ticking entity

>java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.Entity.func_184191_r(Entity.java:1919) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:immersiveengineering:IE wire damage,xf:fml:quark:redirect-fire-resistance}
	at net.minecraft.entity.ai.goal.HurtByTargetGoal.func_190105_f(SourceFile:92) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.HurtByTargetGoal.func_75249_e(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:119) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:972) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2410) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:681) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:42) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.ZombieEntity.func_70636_d(ZombieEntity.java:227) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2157) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:429) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:201) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.world.World.func_217390_a(World.java:596) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:121) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

>-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.Entity.func_184191_r(Entity.java:1919)
	at net.minecraft.entity.ai.goal.HurtByTargetGoal.func_190105_f(SourceFile:92)
	at net.minecraft.entity.ai.goal.HurtByTargetGoal.func_75249_e(SourceFile:71)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:119)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:972)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2410)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:681)
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:42)
	at net.minecraft.entity.monster.ZombieEntity.func_70636_d(ZombieEntity.java:227)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2157)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:429)
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:201)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604)

>-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.entity.monster.ZombieEntity)
	Entity ID: 42442
	Entity Name: Зомби
	Entity's Exact location: 565.31, 45.50, -32.30
	Entity's Block location: World: (565,45,-33), Chunk: (at 5,2,15 in 35,-3; contains blocks 560,0,-48 to 575,255,-33), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Entity's Momentum: -0.34, 0.35, 0.18
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:596)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397)

>-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Valerik_a'/86, l='ServerLevel[Выживание с котиком :3]', x=573.25, y=44.00, z=-36.03]]
	Chunk stats: ServerChunkCache: 4850
	Level dimension: minecraft:overworld
	Level spawn location: World: (-160,66,112), Chunk: (at 0,4,0 in -10,7; contains blocks -160,0,112 to -145,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7829518 game time, 9113235 day time
	Level name: Выживание с котиком :3
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 68867 (now: false), thunder time: 18338 (now: false)
	Known server brands: vanilla, forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:121)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at java.lang.Thread.run(Unknown Source)

>-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3910312768 bytes (3729 MB) / 7180648448 bytes (6848 MB) up to 7180648448 bytes (6848 MB)
	CPUs: 16
	JVM Flags: 10 total; -Xmn128M -Xmx6840M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine%201.16.1%20HD%20U%20G2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.75.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.75
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		EnchantedBookRedesign 3.0.jar Enchanted Book Redesign {enchantedbookredesign@3.0 DONE}
		JustEnoughItems 7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		AbnormalsCore v2.0.0.jar Abnormals Core {abnormals_core@2.0.0 DONE}
		BuzzierBees 2.0.0.jar Buzzier Bees {buzzier_bees@2.0.0 DONE}
		Caelus 2.0-beta5.jar Caelus API {caelus@FORGE-1.16.1-2.0-beta5 DONE}
		Reap 1.0.2.jar Reap Mod {reap@1.16.1-1.0.2 DONE}
		NoAutoJump 1.jar No Auto-Jump {noautojump@1.16.1-1 DONE}
		InvTweaks 1.0.5.jar Inventory Tweaks Renewed {invtweaks@1.16.1-1.0.5 DONE}
		ExtraBoats 1.4.0.jar Extra Boats {extraboats@1.4.0 DONE}
		Neat+ 1.7-23.jar Neat {neat@1.7-23 DONE}
		BetterCaves 1.0.jar YUNG's Better Caves {bettercaves@1.16.1-1.0 DONE}
		XaerosWorldMap 1.7.4.jar Xaero's World Map {xaeroworldmap@1.7.4 DONE}
		LightOverlay 5.4.1.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		CookingForBlockheads 9.0.0.jar Cooking for Blockheads {cookingforblockheads@9.0.0 DONE}
		Controlling 7.0.0.2.jar Controlling {controlling@7.0.0.2 DONE}
		Сomforts 3.0.jar Comforts {comforts@FORGE-1.16.1-3.0 DONE}
		[CORE] Placebo 1-4.0.1.jar Placebo {placebo@4.0.1 DONE}
		[CORE] Citadel 1.2.0.jar Citadel {citadel@1.2.0 DONE}
		NaturesCompass 1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}
		SimpleStorageNetwork 1.0.0.jar Simple Storage Network {storagenetwork@1.16.1-1.0.0 DONE}
		NamePain 1.2.3.jar Name Pain {namepain@1.2.3 DONE}
		DecorativeBlocks 7a.jar Decorative Blocks {decorative_blocks@7a DONE}
		VanillaTweaks 1.5.29.jar VanillaTweaks {vanillatweaks@1.16.1-1.5.29 DONE}
		CurioOfUndying 4.0.jar Curio of Undying {curioofundying@FORGE-1.16.1-4.0 DONE}
		Bookshelf 6.1.11.jar Bookshelf {bookshelf@6.1.11 DONE}
		SnowUnderTrees v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		GuardVillagers 1.1.1.jar Guard Villagers {guardvillagers@1.1.1 DONE}
		CreeperConfetti 3.2.jar Creeper Confetti {creeperconfetti@3.2 DONE}
		ForgivingVoid 5.0.0.jar Forgiving Void {forgivingvoid@5.0.0 DONE}
		LightingWand 1.6.1.jar Lighting Wand {lightingwand@1.6.1 DONE}
		Morpheus 4.2.55.jar Morpheus {morpheus@version DONE}
		Hwyla 1.10.10-B77.jar Waila {waila@1.10.10-B77_1.16.1 DONE}
		ToastControl 4.0.0.jar Toast Control {toastcontrol@4.0.0 DONE}
		JEITweaker 1.0.1.2.jar JEI Tweaker {jeitweaker@1.0.1.2 DONE}
		CarpetStairsMod v1.4.6.jar Carpet Stairs Mod {carpetstairsmod@1.4.6 DONE}
		FPSReducer 1.17.jar FPS Reducer {fpsreducer@mc1.16.1-1.17 DONE}
		JustEnoughResources 0.11.0.79.jar Just Enough Resources {jeresources@0.11.0.79 DONE}
		CraftTweaker 7.0.0.14.jar CraftTweaker {crafttweaker@7.0.0.14 DONE}
		forge-1.16.1-32.0.75-universal.jar Forge {forge@32.0.75 DONE}
		IronChest 11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		SoundDeviceOptions 1.4.0.jar Sound Device Options {sounddeviceoptions@1.4.0 DONE}
		CraftingTweaks 12.0.4.jar Crafting Tweaks {craftingtweaks@12.0.4 DONE}
		forge-1.16.1-32.0.75-client.jar Minecraft {minecraft@1.16.1 DONE}
		TheEndergeticExpansion 2.0.0.jar The Endergetic Expansion {endergetic@2.0.0 DONE}
		EnchantmentDescriptions 3.0.2.jar EnchantmentDescriptions {enchdesc@3.0.2 DONE}
		MouseTweaks 2.13.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ImmersiveEngineering 0.16-109.jar Immersive Engineering {immersiveengineering@0.16-109 DONE}
		RingOfGrowth 1.2.0.jar Ring of Growth {ring_of_growth@1.2.0 DONE}
		Ding 1.1.0.jar Ding {ding@1.1.0 DONE}
		Car 1.0.7.jar Ultimate Car Mod {car@1.16.1-1.0.7 DONE}
		Curios 3.0.jar Curios API {curios@FORGE-1.16.1-3.0 DONE}
		SavageAndRavage 2.0.0.jar Savage & Ravage {savageandravage@2.0.0 DONE}
		XaerosMinimap 20.17.0.jar Xaero's Minimap {xaerominimap@20.17.0 DONE}
		Rats 6.0.5.jar Rats {rats@6.0.5 DONE}
		PamHC2FoodCore 1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		Gravestone 1.0.3.jar Gravestone Mod {gravestone@1.16.1-1.0.3 DONE}
		FastWorkbench 4.1.1.jar FastWorkbench {fastbench@4.1.1 DONE}
		Polymorph 0.11.jar Polymorph {polymorph@FORGE-1.16.1-0.11 DONE}
		[CORE] AutoRegLib 1.6-42.jar AutoRegLib {autoreglib@1.6-42 DONE}
		Quark-r2.2-258.jar Quark {quark@r2.2-258 DONE}
		Sit v1.3.jar Sit {sit@v1.3 DONE}
		AngelRing 1.3.0.jar Angel Ring {angelring@1.3.0 DONE}
		Backpacked 1.16.1.jar Backpacked {backpacked@1.4.4 DONE}
		IKnowWhatImDoing 3.0.1.jar I Know What I'm Doing {iknowwhatimdoing@1 DONE}
		FastFurnace 4.0.0.jar FastFurnace {fastfurnace@4.0.0 DONE}
		MrCrayfish's Furniture Mod 7.0.0-pre17.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre17 DONE}
		AppleSkin 1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		CuriousElytra 3.0.jar Curious Elytra {curiouselytra@FORGE-1.16.1-3.0 DONE}
		AI-Improvements 0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		CherishedWorlds 4.0.jar Cherished Worlds {cherishedworlds@FORGE-1.16.1-4.0 DONE}
		[CORE] ClothConfig4.0.1.jar Cloth Config v4 API {cloth-config@4.0 DONE}
		TrampleStopper 2.0.0.1.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.1-universal DONE}
		bwncr-1.16.1-3.6.15.jar Bad Wither No Cookie Reloaded {bwncr@1.16.1-3.6.15 DONE}
		FastLeafDecay v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		CosmeticArmorReworked v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.1-v1a DONE}
		BetterMineshafts 1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.16.1-1.3 DONE}
		XPTome v1.1.6.jar XP Tome {xpbook@v1.1.6 DONE}
		DefaultOptions 12.0.1.jar Default Options {defaultoptions@12.0.1 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Valerik_a'/86, l='ServerLevel[Выживание с котиком :3]', x=573.25, y=44.00, z=-36.03]]
	Data Packs: vanilla, mod:appleskin, mod:craftingtweaks (incompatible), mod:crafttweaker, mod:fastbench (incompatible), mod:fastfurnace (incompatible), mod:fastleafdecay, mod:forge, mod:invtweaks (incompatible), mod:jei (incompatible), mod:jeitweaker, mod:mousetweaks (incompatible), mod:placebo (incompatible), mod:sit, mod:toastcontrol (incompatible), mod:xaeroworldmap, mod:aiimprovements (incompatible), mod:naturescompass (incompatible), mod:jeresources (incompatible), mod:reap, mod:enchantedbookredesign, mod:abnormals_core, mod:buzzier_bees, mod:caelus (incompatible), mod:noautojump (incompatible), mod:extraboats, mod:bettercaves, mod:lightoverlay-forge (incompatible), mod:controlling, mod:comforts (incompatible), mod:citadel (incompatible), mod:storagenetwork (incompatible), mod:namepain, mod:decorative_blocks, mod:vanillatweaks, mod:curioofundying (incompatible), mod:bookshelf (incompatible), mod:snowundertrees, mod:guardvillagers (incompatible), mod:creeperconfetti (incompatible), mod:forgivingvoid (incompatible), mod:lightingwand, mod:morpheus (incompatible), mod:carpetstairsmod, mod:fpsreducer, mod:ironchest, mod:sounddeviceoptions (incompatible), mod:endergetic (incompatible), mod:enchdesc (incompatible), mod:immersiveengineering (incompatible), mod:ring_of_growth (incompatible), mod:ding, mod:curios (incompatible), mod:savageandravage, mod:xaerominimap, mod:rats (incompatible), mod:pamhc2foodcore (incompatible), mod:gravestone, mod:polymorph, mod:autoreglib (incompatible), mod:quark, mod:angelring (incompatible), mod:backpacked, mod:iknowwhatimdoing (incompatible), mod:curiouselytra (incompatible), mod:cherishedworlds (incompatible), mod:cloth-config, mod:tramplestopper (incompatible), mod:bwncr (incompatible), mod:cosmeticarmorreworked (incompatible), mod:bettermineshafts, mod:xpbook, mod:defaultoptions (incompatible), mod:waila, mod:neat (incompatible), mod:cookingforblockheads (incompatible), mod:car, mod:cfm
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.1_HD_U_G2
	OptiFine Build: 20200802-005745
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
