### ISSUE TITLE
"Mod is not signed" and "@mods should be in separate coremod jar."

### ISSUE THREAD

**Issue by Lynnix01** [AlexModGuy/Rats#402]
I downloaded the latest version of Rats and had this issue come up. I deleted it and tried downloading an older version, same problem. Not quite sure what I should do to fix this, but for now I'm going to delete from mods folder and play without. Hope you help me out, thank you! 

`[11:13:27]` [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:13:27] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:13:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[11:13:27] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[11:13:27] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 8.1:amd64:6.3, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64
[11:13:27] [main/INFO] [FML]: Searching C:\Users\lynni\OneDrive\Desktop\Downloaded\MultiMC\instances\1.12.2 Witch,WW,VP,Druid\.minecraft\mods for mods
[11:13:27] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in rats-3.2.11-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:13:27] [main/WARN] [FML]: The coremod ratscore (com.github.alexthe666.rats.server.asm.RatsPlugin) is not signed!
[11:13:27] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:13:27] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[11:13:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:13:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:13:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:13:29] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[11:13:29] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[11:13:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:13:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[11:13:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/server/misc/RatsRuntimePatcher
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at com.github.alexthe666.rats.server.asm.RatsPlugin.getASMTransformerClass(RatsPlugin.java:18)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:13:29] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 12 more
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/asm/RuntimePatcher
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	... 14 more
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.server.asm.RuntimePatcher
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[11:13:29] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 18 more
[11:13:29] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[11:13:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[11:13:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[11:13:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[11:13:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[11:13:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[11:13:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.`

**Comment by GizmoTheMoonPig** [comment]
no longer an issue in modern versions, not only do we not use LLibrary but the ASM referenced no longer exists
